default_language_version:
    python: python3.8
default_stages:
- commit
- push
exclude: ^pending_rebuild/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.4.0'
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: check-docstring-first
    -   id: check-json
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    - id: bandit
      args: [--skip, "B101"]
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
